### ISSUE TITLE
Decide on color palettes

### ISSUE THREAD

**Issue by JacobPernell** [JacobPernell/songbird#71]
Here are a handful of initial ideas:

1) https://coolors.co/4c212a-01172f-f4c3dd-178298-91e5f6

2) https://coolors.co/231942-45b1e8-e079a5-d8d8f6-9f86c0

3) https://coolors.co/0093ca-fbb511-d00000-2e282a-003866

4) https://coolors.co/ffbfbf-ceeae7-623cea-e9f1f7-54426b

5) https://coolors.co/a21e3a-f2cae2-f8fbff-b2c9de-2b59c3

6) https://coolors.co/e63946-f1faee-a8dadc-457b9d-1d3557

7) https://coolors.co/1a535c-4ecdc4-f7fff7-ff6b6b-ffe66d

@mskalandunas

**Comment by mskalandunas** [comment]
@JacobPernell I love this one: https://coolors.co/1a535c-4ecdc4-f7fff7-ff6b6b-ffe66d

**Comment by JacobPernell** [comment]
Nice! That's one of my favs too. I say we roll with it!

https://coolors.co/1a535c-4ecdc4-f7fff7-ff6b6b-ffe66d it is!
